version: '2.0'
services:
  mysql:
    image: mysql:5
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: ft_transcendence
  frontend:
    build:
      context: ./frontend
    ports:
    - "3000:3000"
    expose:
    - "3000"
  backend:
    build:
      context: ./backend
    ports:
    - "3001:3001"
    expose:
    - "3001"
    depends_on:
      - "mysql"
    links:
      - "mysql:ft-transcendence-mysql"
  nginx:
    image: nginx
    restart: always
    volumes:
      - "./docker/nginx/default.compose.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
    - "80:80"
    expose:
    - "80"
    depends_on:
      - "backend"
      - "frontend"
    links:
      - "backend:ft-transcendence-backend"
      - "frontend:ft-transcendence-frontend"